# .goreleaser.yml
builds:
  - binary: spyder
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  github:
    owner: 5sigma
    name: homebrew-tap
  homepage: https://github.com/5Sigma/spyder
  description: API testing in the terminal.
fpm:
  vendor: 5sigma
  homepage: https://github.com/5Sigma/spyder
  maintainer: Joe Bellus <joe@5sigma.io>
  description: API testing in the terminal.
  license: Apache 2.0
  formats:
    - deb
    - rpm
snapcraft:
  name: spyder
  summary: API testing and request utility for the console
  description: |
    Spyder makes requesting API endpoints easy. You define an API using simple
    configuration files and tasks. These files can then be versioned making
    collaboration easy and painless.
  grade: stable
  confinement: strict
